name: UB22.04-mpich
on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install freeglut3-dev liblapack-dev libhdf5-dev libgsl-dev cmake mpich
    - name: configure
      run: |
        export PREFIXPSD=/home/runner/psd
        autoreconf -i && ./configure --prefix=$PREFIXPSD --with-dependencies
    - name: make
      run: |
        export PREFIXPSD=/home/runner/psd
        cd ext && make && cd ..
        export PATH=$PREFIXPSD/bin:$PATH
        export LD_LIBRARY_PATH=$PREFIXPSD/lib:$LD_LIBRARY_PATH
        source $PREFIXPSD/mfront-env.sh
        ./configure --prefix=$PREFIXPSD --with-mgis=$PREFIXPSD --with-mfront=$PREFIXPSD --with-FreeFEM=$PREFIXPSD/bin --with-Gmsh=$PREFIXPSD/bin  
        make && make install
    - name: make check
      run: make check
